### ISSUE TITLE
possible error

### ISSUE THREAD

**Issue by baovuong** [golayalgorithm/molekel_helper#1]
if you can look into mode10.txt or mode10.xyz, look at line 396. that might be the cause of the error.

**Comment by paivankakkara** [comment]
Ahhhhh that's what we saw with the shorter one too.  I think this may be
fine to delete.  Feel free to delete and check format.  I'll check if it
works fine on Molekel tomorrow.

**Comment by baovuong** [comment]
yup. that fixed it.

**Comment by paivankakkara** [comment]
Alright awesome!

**Comment by baovuong** [comment]
if you have more problems to report, go ahead and post an issue on the Issues page.
